### ISSUE TITLE
v3.0.2 go import issue

### ISSUE THREAD

**Issue by ccamel** [vrecan/death#44]
Context:

```
> go version
go version go1.15.5
```

I'm trying to upgrade project `vrecan/death` to version `v3.0.2` without success.

For instance:

```
> go get gopkg.in/vrecan/death.v3
go: gopkg.in/vrecan/death.v3 upgrade => v3.0.1+incompatible
```

→ Not the latest version.

If I try to specify the latest one:

```
> go get github.com/vrecan/death@v3.0.2
go get github.com/vrecan/death@v3.0.2: github.com/vrecan/death@v3.0.2: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3
```

→ it fails.

Though, I found a way to solve this issue using the latest commit on the branch master, but this has some drawbacks.

```
> go get github.com/vrecan/death@master
go: github.com/vrecan/death master => v0.0.0-20200705210906-920f972a884a
```

Is there something more I can do?

Thx.

**Comment by grindlemire** [comment]
Hey! Sorry this took so long to get to, I must have missed the notification and just saw an open issue. I think this is a bug in the go.mod file with a simple fix. I'll update it and cut a new release.

**Comment by grindlemire** [comment]
Note that as a part of integrating with go modules you will need to change your imports to match go recommendations. So your imports (and go get command) will need to reference `github.com/vrecan/death/v3` rather than `github.com/vrecan/death`. I updated the README with the new import statement for clarification.
